server {
    listen 80;
    server_name 3dmap-pzks;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /panoramas/ {
        proxy_pass http://minio:9000/panoramas/;
    }
}