name: CI Pipeline

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate docker-compose
        run: docker compose config

      - name: Generate dummy SSL certs for Nginx validation
        run: |
          mkdir -p ./certbot/conf/live/virtual-pzks.chnu.edu.ua
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout ./certbot/conf/live/virtual-pzks.chnu.edu.ua/privkey.pem \
            -out ./certbot/conf/live/virtual-pzks.chnu.edu.ua/fullchain.pem \
            -subj "/CN=virtual-pzks.chnu.edu.ua"

      - name: Validate nginx config
        run: |
          docker compose up -d
          docker compose exec -T nginx nginx -t
          docker compose down

      - name: Validate HTML
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          node:20 bash -c "
            npm install -g htmlhint &&
            htmlhint /app/nginx/index.html
          "

      - name: Validate JavaScript
        run: echo "JavaScript validation skipped"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/3dmap

            git pull origin main

            docker-compose down
            docker-compose up -d